### ISSUE TITLE
Flux dispatcher using Mobx

### ISSUE THREAD

**Issue by luisherranz** [vinej/react-portal#2]
Have you thought about a dispatcher in which actions are mobx observables as well?

I don't have a specific implementation in mind yet, but maybe it would have certain benefits.

**Comment by vinej** [comment]
Not really and I don't know if there is certain benefits. I'll think about it.
Until now the goal of the dispatch is to have a middleware before the modification of the store.

I just commit an authorization middleware to be able to know which actions the user can do. Like that it's possible to hide, disable certains actions. For sure, you have to do the same validation with the backend.

Thanks

**Comment by vinej** [comment]
closed
