### ISSUE TITLE
in need of a tip to get login working for me.

### ISSUE THREAD

**Issue by pietgk** [vinej/react-portal#3]
Hello,

i installed and started react-portal and react-portal-server as described.

on the first request: 
http://localhost:3090/api/actions?project=all&language=en
i get a 401 (Unauthorized).

i did not change index.js or config.js.
i also did not create any database (just started mongod)

could you give me a hint where to look for further reading / a tip to resolve this.

(answer could also help others that try to get it running the first time :-) )

Thx in advance

**Comment by vinej** [comment]
I will complete the documentation tonight to be sure that everything is still working when you starts with an empty database.
- try to test the API without the UI with Chrome PostMan. It's the best way to debug things like that with an REST API
- every request to the API needs a token. The token is retrieve when you "signup" the first time and when you "signin" after that.
- probably that you have to create somes tables to setup the user security. see the react-portal-server / controllers / action.js flle (Right and Role), but I don't think that the error is coming from there.

I will send you more information later.

Thanks

**Comment by vinej** [comment]
I did the test and It worked for me with an empty database.
- I added into the documentation to create the folder c:\data\db, because mongodb is putting the database there
- you don't have to create tables for security, because the security for actions is not activated by default

=> Don't forget to : 'signup' the first time. After that you use "signin"

When you signed up :  
- create a new Dashboard
- add widgets to the current Dashboard
- add todo 
- etc.

To be sure use the latest version

I hope it will help you

Thanks

**Comment by vinej** [comment]
Note: the widget "todo" is broken, use the 'helps' widget, this one is a test with ag-grid and it's working.

**Comment by pietgk** [comment]
i tested with a simple mongod and with mongod --config /usr/local/etc/mongod.conf

the first 2 requests i get are:

[nodemon] starting `node index.js`
Server listening on: 3090
::1 - - [14/Jun/2016:20:50:32 +0000] "OPTIONS /api/actions?project=all&language=en HTTP/1.1" 204 - "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
::1 - - [14/Jun/2016:20:50:32 +0000] "GET /api/actions?project=all&language=en HTTP/1.1" 500 2164 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"

/api/actions check for authorisation and gives the Unauthorized

i am not getting the UI to do a signup, client console is:
bundle.js:29676[mobx] Deprecated: extras.SimpleEventEmitter is deprecated and will be removed in the next major releasedeprecated @ bundle.js:29676SimpleEventEmitter @ bundle.js:29636mrFactory @ bundle.js:30861(anonymous function) @ bundle.js:31051(anonymous function) @ bundle.js:31057__webpack_require__ @ bundle.js:20(anonymous function) @ bundle.js:30730__webpack_require__ @ bundle.js:20(anonymous function) @ bundle.js:30092__webpack_require__ @ bundle.js:20(anonymous function) @ bundle.js:27374__webpack_require__ @ bundle.js:20(anonymous function) @ bundle.js:27327__webpack_require__ @ bundle.js:20(anonymous function) @ bundle.js:27178__webpack_require__ @ bundle.js:20(anonymous function) @ bundle.js:25917__webpack_require__ @ bundle.js:20(anonymous function) @ bundle.js:25787__webpack_require__ @ bundle.js:20(anonymous function) @ bundle.js:59__webpack_require__ @ bundle.js:20(anonymous function) @ bundle.js:40(anonymous function) @ bundle.js:43
bundle.js:27312action auth_check_token Object {type: "auth_check_token"}
bundle.js:27312action auth_set_authorizations Object {type: "auth_set_authorizations"}
:3090/api/actions?project=all&language=en:1 GET http://localhost:3090/api/actions?project=all&language=en 401 (Unauthorized)
bundle.js:27312 action auth_error Object {type: "auth_error", payload: "Unauthorized"}

(looking further into this, (took a look at the Udemy course to get more jwt knowledge))

**Comment by pietgk** [comment]
patched auth_store.js:
    const token = localStorage.getItem('token')
    if (false/_token_/) {
      const name = localStorage.getItem('name')
      transaction( () 

gives me an initial screen

seems localstore return a token somehow

its late for me i'm getting some sleep

**Comment by vinej** [comment]
Thank you for your patience and to have found the problem. I have actually tested only on Windows. In the future I will do some test with a mac environment to catch this kind of bug.

I did some modifications to ensure that the token is ok and to return to the login screen if there is an error with the authentification.

Thanks
.

**Comment by pietgk** [comment]
from my view you may close this issue.
